### PR TITLE
Feature/test cases by beni

### LINKED ISSUE #134: Settler drills
See documentation (beadando_5) page 11.
Don't forget the test fixture (comm diagram) from page 28.
This might be 1 test case.

### LINKED ISSUE #135: Robot drills
See documentation (beadando_5) page 12.
Don't forget the test fixture (comm diagram) from page 28.
This might be 1 test case.

### LINKED ISSUE #136: Settler moves to asteroid
See documentation (beadando_5) page 12.
Don't forget the test fixture (comm diagram) from page 22-23.
This might be 2 different test case (because of comm diagrams).

### LINKED ISSUE #137: Robot moves to asteroid
See documentation (beadando_5) page 13.
Don't forget the test fixture (comm diagram) from page 22.
This might be 2 different test cases (because of comm diagrams).

### LINKED ISSUE #138: Settler moves through teleport / Settler tries to use teleport gate without active pair
See documentation (beadando_5) page 13-14.
Don't forget the test fixture (comm diagram) from page 29.
Be aware, this is 2 different test cases.

### PR DESCRIPTION
**Pull request by poiuztrewq1**
closes #134 
closes #135 
closes #136 
closes #137 
closes #138

### CODE REVIEW

**Comment by vercibar** [comment]
A lot has changed with master since this branch was created. Input is now handled in load() of each testcase. Need a slight refactor

**Review by triszt4n — APPROVED** [review]
# 🤙

**Comment by triszt4n** [comment]
> A lot has changed with master since this branch was created. Input is now handled in load() of each testcase. Need a slight refactor

I guess, there are no input needed in these test cases. (Or am I wrong? I can't see any Logger queries)

**Comment by poiuztrewq1** [comment]
> A lot has changed with master since this branch was created. Input is now handled in load() of each testcase. Need a slight refactor

I still think this violates the request of the lab guide `A szkeleton osztályai csak asszociációkat tárolnak, egyéb állapotot nem!`, but at this point I don't care..

**Review by vercibar — APPROVED** [review]

**Pull request merged**
